// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-zhQdaXEB6FiGlxSTzxZaane4xyHAJn0',
    appId: '1:854634233048:web:8c8874162402062a4a6bad',
    messagingSenderId: '854634233048',
    projectId: 'sellarc',
    authDomain: 'sellarc.firebaseapp.com',
    storageBucket: 'sellarc.firebasestorage.app',
    measurementId: 'G-06QXJX0SYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Kv7vqRIIOKk4HHvjJ8Lbc0C2hi8CDbc',
    appId: '1:854634233048:android:82c38fec284b0ce94a6bad',
    messagingSenderId: '854634233048',
    projectId: 'sellarc',
    storageBucket: 'sellarc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTSFB7n3zKJFbCeL8YM6EtNiOezTDA4g',
    appId: '1:854634233048:ios:7e05c62c09b9b3324a6bad',
    messagingSenderId: '854634233048',
    projectId: 'sellarc',
    storageBucket: 'sellarc.firebasestorage.app',
    androidClientId: '854634233048-ias9efm0p7p9mh2sco92jfnat2oggquj.apps.googleusercontent.com',
    iosClientId: '854634233048-h5n0sfjfehgk246hpogpje8tc4dbpij0.apps.googleusercontent.com',
    iosBundleId: 'com.sellarc.sellarc',
  );

}