name: sellarc
description: "Sales management for everybody"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Application dependencies.
# These are packages that the application code directly depends on.
# For more information about managing dependencies, see https://flutter.dev/to/dependencies.
dependencies:
  flutter:
    sdk: flutter

  # UI and Theming
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  #google_fonts: ^6.1.0 # Uncomment if you plan to use Google Fonts
  smooth_page_indicator: ^1.2.1

  # State Management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1 # Added Google Sign-In

  # Routing
  go_router: ^16.0.0

  # Utility
  intl: ^0.18.0
  shared_preferences: ^2.0.1
  #dio: ^5.4.0 # Uncomment if you plan to use Dio for HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  build_runner: ^2.4.7
  riverpod_generator: ^2.6.5 # Moved here as it's a code generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
